#+title: Emacs Dote Files

My personal Emacs configuration.

* Features
- Evil keybindings, but lighter.
- Minimal, elegant interface. 
- Modular. Codes are splitted into ~init-***~ modules.

Support Emacs version 30.0 plus.
* Dependency
** Fonts
On macOS:
[[https://github.com/epk/SF-Mono-Nerd-Font][SF-Mono-Nerd-Font]] can be installed via:
~brew tap epk/epk~
~brew install font-sf-mono-nerd-font~

iA writer fonts are available in https://github.com/iaolo/iA-Fonts.

arch linux:
~SFMono Nerd Font~, ~Libertinus Sans~, ~Apple Color Emoji~ and ~iA Writer Duospace~ are available either in arch repository or as AUR.

** Input methods
Refer to [[https://github.com/laishulu/emacs-smart-input-source][emacs smart input source]] and [[https://github.com/DogLooksGood/emacs-rime][emacs-rime]] for instructions on installation.
Note that you need to update the value of ~rime-emacs-module-header-root~ after each upgrade of Emacs.

** External Program
~rg~ package requires ~rg~ program.
~emacs-opencc~ package requires ~opencc~ program.
~goldendict~ package (in linux) requires ~goldendict~ program.

On mac, ~gls~ program is preferred for Dired.
This is usually installed by ~emacs-plus~ package.
